### ISSUE TITLE
Adapter works only if Auth is disabled [Neo4j v2.2.0]

### ISSUE THREAD

**Issue by monkeythecoder** [natgeo/sails-neo4j#11]
I'm trying the whole *ActivityStreams* repo and when I lifted the app the following error was displayed

```bash
An error has occured when trying to connect to Neo4j:

/mypath/activitystreams/node_modules/sails-neo4j/lib/connection.js:15
          throw err;
                ^
Error
    at ClientRequest.<anonymous> (/mypath/activitystreams/node_modules/sails-neo4j/node_modules/neo4j-js/lib/Neo4jApi.js:227:13)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient (http.js:1693:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
    at Socket.socketOnData (http.js:1588:20)
    at TCP.onread (net.js:528:27)
```

after so much I managed to make it work setting the file * conf/neo4j-server.properties* to false in this line
```java
# Disable authorization
dbms.security.auth_enabled=false
```
But this could be a future security issue, any ideas on how to fix this?

**Comment by lsvx** [comment]
@monkeythecoder, thank you for raising this issue. We did not consider HTTP authentication when we built this adapter and, in fact, never ran into the problem in the first place.

To be sure, with authentication enabled in your Neo4j conf, do you get a `401` when you curl Neo4j?

````bash
curl -I http://127.0.0.1:7474/db/data/
````

This Sails adapter is built on https://github.com/bretcope/neo4j-js but they do not document how to enable authentication headers, so I may need to raise an issue with the maintainer.

Thanks,
Lucas

**Comment by lsvx** [comment]
@monkeythecoder,
I re-read the Neo4j docs and realized that their authentication scheme uses the basic authentication scheme for authorization. Can you please try curling:

````shell
curl -I http://<USER>:<PASSWORD>@127.0.0.1:7474/db/data/
````

substituting in the correct `<USER>`, `<PASSWORD>`, host, and port?

If that works, that is you receive a `200`, I think you should be able to define your Neo4j connection in your `connections.js` conf file like so:
````json
module.exports = {
    "neo4j": {
        "adapter": "sails-neo4j",
        "protocol": "http://",
        "port": 7474,
        "host": "<USER>:<PASSWORD>@localhost",
        "base": "/db/data/"
    }
}
````

Please give this a try and let me know how this goes.

-Lucas

**Comment by monkeythecoder** [comment]
@lsvx Hey, that worked pretty well. We should update the readme with the new info. Thanks!
