### ISSUE TITLE
status

### ISSUE THREAD

**Issue by johntom** [natgeo/sails-neo4j#12]
Hi,
I'm attending GraphDays in NYC today and curious as to the status of this project. WIll it support Sails10/11 and neo4j 2.2.
TIA
John

**Comment by lsvx** [comment]
John,

We are using this repository in production with Sails 0.10.5 and Neo4j 2.2.1.

If you look through our releases, you'll find that in February we published a version that added support for Sails up to 0.10.5. This library should work with Sails 0.11.0 but is simply not tested against it.

Best,
Lucas

**Comment by johntom** [comment]
Thanks!
